#!/usr/bin/env python

import subprocess, re, shlex
import appindicator, glib, gtk, requests, signal, time, pynotify, threading, gobject

APPINDICATOR_ID = 'internet-check'
PYNOTIFY_ID = 'internet-check'
ping_host_name = "google.com"

class InternetCheck:
	def __init__(self):
		# param1: appindicator identifier
		# param2: appindicator default icon name
		# param3: appindicator category
		self.indicator = appindicator.Indicator(APPINDICATOR_ID, gtk.STOCK_NO, appindicator.CATEGORY_COMMUNICATIONS)

		# activate the status of the indicator
		self.indicator.set_status( appindicator.STATUS_ACTIVE )

		# initiate the pynotify using some unique app ID
		pynotify.init(PYNOTIFY_ID)

		# Build the main menu
		self.build_main_menu()

		self.ping_timeout = 3
		self.update_interval = 5
		self.ping_paused = False

		self.show_notification("Internet Check", "Now tracking the ping continuously! You can pause the tracking from the menu.", 3000)

		self.indicator.set_icon( gtk.STOCK_NO )
		self.indicator.set_label( "--" )

		self.update_ui()

		glib.timeout_add_seconds ( self.update_interval, self.update_timeout )


	def build_main_menu(self):
		# trigger to build the menu
		self.menu = gtk.Menu()

		# create a menu item for showing about indicator section
		item_about = gtk.MenuItem("Internet Check Indicator")
		self.menu.append( item_about )

		# create a menu item for pausing and resuming the ping operation
		item_pause = gtk.MenuItem("Pause")
		item_pause.connect('activate', self.pause_resume)
		self.menu.append( item_pause )

		# create a menu item for exiting the app
		item_exit = gtk.MenuItem("Exit")
		item_exit.connect( 'activate', self.exit_indicator )
		self.menu.append( item_exit )

		self.menu.show_all()
		self.indicator.set_menu ( self.menu )


	def ping(self, host_name):
		# pings google.com and returns a dot . on success and an X on failure
		ping_command = "ping -i " + str(self.ping_timeout) + " -c 1 " + host_name
		process = subprocess.Popen( shlex.split( ping_command ), stdout = subprocess.PIPE )
		output = process.stdout.read()
		matches = re.findall(r"time=[0-9]\w+", output)
		if len(matches):
			# print matches[0].split("=")[-1]
			return matches[0].split("=")[-1]
		else: 
			return False
		# return check_output( ["sh", "-c", "{ timeout " + str( self.ping_timeout ) + " ping -w 3 -c 2 -i 1 google.com > /dev/null 2>&1 && echo -n . ; } || { echo -n X ; }"] )
	

	# this function will be called every {update_interval} seconds by glib
	def update_timeout(self):
		
		if not self.ping_paused:
			self.update_ui()

		# returning True so that it doesn't get exited from timeout_add_seconds function
		return True


	def update_ui(self):
		# set the loading text
		curr_label = self.indicator.get_label()
		self.indicator.set_label( curr_label + "(Loading)" )

		# ping the host and get the response
		ping_response = self.ping(ping_host_name)

		## TODO ##
		if ping_response == False:
			# if False is received, play connection_down sound
			# and change the icon to STOCK_STOP one
			self.indicator.set_icon( gtk.STOCK_NO )
			self.indicator.set_label( "--" )
		else:
			# otherwise, change to STOCK_ON icon.
			self.indicator.set_icon( gtk.STOCK_YES )
			self.indicator.set_label( str( ping_response ) + " ms" )


	def pause_resume(self, source):
		# click on resume
		if self.ping_paused:
			self.ping_paused = False
			self.indicator.set_label("Resuming...")
			source.set_label("Pause")
			self.show_notification("Internet Check", "Ping checking has been resumed!", 1000)
			self.update_ui()
		# click on pause
		else:
			self.ping_paused = True
			curr_label = self.indicator.get_label()
			self.indicator.set_label(curr_label + "(Paused)")
			source.set_label("Resume")
			self.show_notification("Internet Check", "Ping checking has been paused!", 1000)


	def show_notification(self, title="Title", msg="Message", timeout=1000):
		notification = pynotify.Notification(title, msg)
		notification.set_timeout(timeout)
		notification.show()


	def exit_indicator(self, source):
		gtk.main_quit()
		self.show_notification("Internet Check", "Exiting the app-indicator.", 3000)


	def main(self):
		gtk.main()


if __name__ == "__main__":
	# For making Ctrl+C do it's default action
	signal.signal(signal.SIGINT, signal.SIG_DFL)
	indicator = InternetCheck()
	indicator.main()
