#!/usr/bin/env python

import subprocess, re, shlex
import appindicator, glib, gtk, requests, signal, time, pynotify, threading, gobject

APPINDICATOR_ID = 'internet-check'
PYNOTIFY_ID = 'internet-check'
ping_host_name = "google.com"


"""
InternetCheck class - main class implementing the entire app-indicator
"""
class InternetCheck:

	"""
	Class constructor
	"""
	def __init__(self):
		# param1: appindicator identifier
		# param2: appindicator default icon name
		# param3: appindicator category
		self.indicator = appindicator.Indicator(APPINDICATOR_ID, gtk.STOCK_NO, appindicator.CATEGORY_COMMUNICATIONS)

		# activate the status of the indicator
		self.indicator.set_status( appindicator.STATUS_ACTIVE )

		# initiate the pynotify using some unique app ID
		pynotify.init(PYNOTIFY_ID)

		# Build the menu
		self.build_menu()

		self.ping_timeout = 3
		self.update_interval = 5
		self.ping_paused = False

		self.show_notification("Internet Check", "Now tracking the ping continuously! You can pause the tracking from the menu.", 3000)

		self.indicator.set_icon( gtk.STOCK_NO )
		self.indicator.set_label( "--" )

		self.update_ui()

		self.timeout_ID = glib.timeout_add_seconds(self.update_interval, self.update_timeout)


	"""
	Method to build the entire menu including the submenu as well
	"""
	def build_menu(self):
		# trigger to build the menu
		self.menu = gtk.Menu()

		# create a menu item for showing about indicator section
		item_about = gtk.MenuItem("Internet Check Indicator")
		self.menu.append( item_about )

		# create menu item for adjusting the ping refresh time
		item_refresh_control = gtk.MenuItem("Adjust refresh time")
		self.menu_refresh_control = gtk.Menu()
		subitem_1 = gtk.RadioMenuItem(None, "5 seconds")
		subitem_1.connect('activate', self.adjust_update_interval)
		self.menu_refresh_control.append(subitem_1)
		group = subitem_1.get_group()
		print group
		subitem_2 = gtk.RadioMenuItem(group[0], "10 seconds")
		subitem_2.connect('activate', self.adjust_update_interval)
		self.menu_refresh_control.append(subitem_2)
		group = subitem_2.get_group()
		print group
		subitem_3 = gtk.RadioMenuItem(group[0], "20 seconds")
		subitem_3.connect('activate', self.adjust_update_interval)
		self.menu_refresh_control.append(subitem_3)
		group = subitem_3.get_group()
		print group
		subitem_4 = gtk.RadioMenuItem(group[0], "30 seconds")
		subitem_4.connect('activate', self.adjust_update_interval)
		self.menu_refresh_control.append(subitem_4)
		group = subitem_4.get_group()
		print group
		item_refresh_control.set_submenu(self.menu_refresh_control)
		self.menu.append(item_refresh_control)

		# create a menu item for pausing and resuming the ping operation
		item_pause = gtk.MenuItem("Pause")
		item_pause.connect('activate', self.pause_resume)
		self.menu.append( item_pause )

		# create a menu item for exiting the app
		item_exit = gtk.MenuItem("Exit")
		item_exit.connect( 'activate', self.exit_indicator )
		self.menu.append( item_exit )

		self.menu.show_all()
		self.indicator.set_menu ( self.menu )


	"""
	Main method implementing the ping functionality,
	returns the ping time if successful ping is observed,
	and False otherwise
	"""
	def ping(self, host_name):
		# pings google.com and returns a dot . on success and an X on failure
		ping_command = "ping -i " + str(self.ping_timeout) + " -c 1 " + host_name
		process = subprocess.Popen( shlex.split( ping_command ), stdout = subprocess.PIPE )
		output = process.stdout.read()
		matches = re.findall(r"time=[0-9]\w+", output)
		if len(matches):
			# print matches[0].split("=")[-1]
			return matches[0].split("=")[-1]
		else: 
			return False
		# return check_output( ["sh", "-c", "{ timeout " + str( self.ping_timeout ) + " ping -w 3 -c 2 -i 1 google.com > /dev/null 2>&1 && echo -n . ; } || { echo -n X ; }"] )
	

	"""
	Method which will be called every {update_interval} seconds by glib
	"""
	def update_timeout(self):
		
		if not self.ping_paused:
			self.update_ui()

		# returning True so that it doesn't get exited from timeout_add_seconds function
		return True


	"""
	Method responsible for updating the label and icon of the app-indicator
	"""
	def update_ui(self):
		# set the loading text
		curr_label = self.indicator.get_label()
		self.indicator.set_label( curr_label + "(Loading)" )

		# ping the host and get the response
		ping_response = self.ping(ping_host_name)

		print ping_response, self.update_interval

		## TODO ##
		if ping_response == False:
			# if False is received, play connection_down sound
			# and change the icon to STOCK_STOP one
			self.indicator.set_icon( gtk.STOCK_NO )
			self.indicator.set_label( "--" )
		else:
			# otherwise, change to STOCK_ON icon.
			self.indicator.set_icon( gtk.STOCK_YES )
			self.indicator.set_label( str( ping_response ) + " ms" )


	"""
	Method to implement the pause/resume feature
	"""
	def pause_resume(self, source):
		# click on resume
		if self.ping_paused:
			self.ping_paused = False
			self.indicator.set_label("Resuming...")
			source.set_label("Pause")
			self.show_notification("Internet Check", "Ping checking has been resumed!", 1000)
			self.update_ui()
		# click on pause
		else:
			self.ping_paused = True
			curr_label = self.indicator.get_label()
			self.indicator.set_label(curr_label + "(Paused)")
			source.set_label("Resume")
			self.show_notification("Internet Check", "Ping checking has been paused!", 1000)


	"""
	Method to implement the adjustment of update interval feature
	"""
	def adjust_update_interval(self, source):
		# find the value of update_interval represented by the source that's selected
		new_update_interval = int(source.get_label().split()[0])

		print "refresh time interval changed to -", new_update_interval

		# update the update_interval value with the new one
		self.update_interval = new_update_interval

		# remove the current timeout_add_seconds event using its event ID
		glib.source_remove(self.timeout_ID)

		# start a new timeout_add_seconds event and update the timeout_ID for later updates
		self.timeout_ID = glib.timeout_add_seconds(self.update_interval, self.update_timeout)


	"""
	Generalized method for showing a notification using pynotify
	"""
	def show_notification(self, title="Title", msg="Message", timeout=1000):
		notification = pynotify.Notification(title, msg)
		notification.set_timeout(timeout)
		notification.show()


	"""
	Method for exiting the app-indicator
	"""
	def exit_indicator(self, source):
		gtk.main_quit()
		self.show_notification("Internet Check", "Exiting the app-indicator.", 3000)


	"""
	Main method for initializing the gtk
	"""
	def main(self):
		gtk.main()


if __name__ == "__main__":
	# For making Ctrl+C do it's default action
	signal.signal(signal.SIGINT, signal.SIG_DFL)
	indicator = InternetCheck()
	indicator.main()
